name: Build Applications
on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-24.04]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check-out repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update &&
          sudo apt-get install build-essential libclang-17-dev clang-17 llvm-17-dev cmake -y
      - name: CMake Configure
        run: |
          mkdir build &&
          cd build &&
          cmake .. -DCMAKE_BUILD_TYPE=MinSizeRel -DLLVMVersion=17
      - name: Build
        run: |
          cd build &&
          cmake --build . &&
          cpack .

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }} Build
          path: | # match what's created for the 3 OSes
            build/golfC-1.2.0-Linux.deb
